using System.Xml.Serialization;
using System.Net;
using System.IO;
using System;


// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "https://www.mmt.com.au", IsNullable = false)]
public partial class MMTPriceList
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PriceListData", typeof(MMTPriceListPriceListData))]
    [System.Xml.Serialization.XmlElementAttribute("Products", typeof(MMTPriceListProducts))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    public static MMTPriceList loadFromURL(string datafeedurl)
    {

        try
        {
            WebClient client = new WebClient();
            client.Headers.Add(HttpRequestHeader.ContentType, "apoplication/xml");
            string response = client.DownloadString(datafeedurl);

            XmlSerializer serial = new XmlSerializer(typeof(MMTPriceList));
            return (MMTPriceList)serial.Deserialize(new StringReader(response));
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return null;
        }
    }



}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListPriceListData
{

    private string retrievalDateField;

    /// <remarks/>
    public string RetrievalDate
    {
        get
        {
            return this.retrievalDateField;
        }
        set
        {
            this.retrievalDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListProducts
{

    private MMTPriceListProductsProduct[] productField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public MMTPriceListProductsProduct[] Product
    {
        get
        {
            return this.productField;
        }
        set
        {
            this.productField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListProductsProduct
{

    private string mMTCodeField;

    private string availabilityField;

    private string ETAField;

    private MMTPriceListProductsProductManufacturer[] manufacturerField;

    private MMTPriceListProductsProductCategory[] categoryField;

    private MMTPriceListProductsProductDescription[] descriptionField;

    private MMTPriceListProductsProductPricing[] pricingField;

    /// <remarks/>
    public string MMTCode
    {
        get
        {
            return this.mMTCodeField;
        }
        set
        {
            this.mMTCodeField = value;
        }
    }

    /// <remarks/>
    public string Availability
    {
        get
        {
            return this.availabilityField;
        }
        set
        {
            this.availabilityField = value;
        }
    }

    /// <remarks/>
    public string ETA
    {
        get
        {
            return this.ETAField;
        }
        set
        {
            this.ETAField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Manufacturer")]
    public MMTPriceListProductsProductManufacturer[] Manufacturer
    {
        get
        {
            return this.manufacturerField;
        }
        set
        {
            this.manufacturerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Category")]
    public MMTPriceListProductsProductCategory[] Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public MMTPriceListProductsProductDescription[] Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pricing")]
    public MMTPriceListProductsProductPricing[] Pricing
    {
        get
        {
            return this.pricingField;
        }
        set
        {
            this.pricingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListProductsProductManufacturer
{

    private string manufacturerCodeField;

    private string manufacturerNameField;

    /// <remarks/>
    public string ManufacturerCode
    {
        get
        {
            return this.manufacturerCodeField;
        }
        set
        {
            this.manufacturerCodeField = value;
        }
    }

    /// <remarks/>
    public string ManufacturerName
    {
        get
        {
            return this.manufacturerNameField;
        }
        set
        {
            this.manufacturerNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListProductsProductCategory
{

    private string categoryNumberField;

    private string parentCategoryNameField;

    private string categoryNameField;

    /// <remarks/>
    public string CategoryNumber
    {
        get
        {
            return this.categoryNumberField;
        }
        set
        {
            this.categoryNumberField = value;
        }
    }

    /// <remarks/>
    public string ParentCategoryName
    {
        get
        {
            return this.parentCategoryNameField;
        }
        set
        {
            this.parentCategoryNameField = value;
        }
    }

    /// <remarks/>
    public string CategoryName
    {
        get
        {
            return this.categoryNameField;
        }
        set
        {
            this.categoryNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListProductsProductDescription
{

    private string shortDescriptionField;

    private string longDescriptionField;

    /// <remarks/>
    public string ShortDescription
    {
        get
        {
            return this.shortDescriptionField;
        }
        set
        {
            this.shortDescriptionField = value;
        }
    }

    /// <remarks/>
    public string LongDescription
    {
        get
        {
            return this.longDescriptionField;
        }
        set
        {
            this.longDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mmt.com.au")]
public partial class MMTPriceListProductsProductPricing
{

    private string yourPriceField;

    private string rRPIncField;

    /// <remarks/>
    public string YourPrice
    {
        get
        {
            return this.yourPriceField;
        }
        set
        {
            this.yourPriceField = value;
        }
    }

    /// <remarks/>
    public string RRPInc
    {
        get
        {
            return this.rRPIncField;
        }
        set
        {
            this.rRPIncField = value;
        }
    }
}
